INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'initial', 'it worked');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'database', 'I found out how to insert current date into the column of my database.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'database', 'I reseeded my db a couple of times because of dumb mistakes.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'database', 'I updated my seed file.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'database', 'I learned how to insert date manually');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'project', 'I decided I would seed my project with posts from my journey of this project.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'project', 'I made my second commit with migration and seed files populated. I will be adding to the seed file through the project to deliver content and for fun :-P');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'github', 'I had some trouble committin changes to github. I did not properly input node_modules in the gitigore file. Yeah, I need more training on this merging branches on github.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'database', 'I just finished connecting my db to the server. I am going to make my first get command. Lets hope there is not too many bugs lol.....I just found a bug with the insert. I have to escape the apostrophe somehow.');
INSERT INTO posts (date, subject, posts) VALUES ('2021-05-24', 'server', 'I got the server to work to with a get request. Only a couple of bugs due to a missing period and used req instead of res.');
INSERT INTO posts (date, subject, posts) VALUES (2021-05-24, 'database', 'added the timestamp function');
INSERT INTO posts (date, subject, posts) VALUES (2021-05-24, 'database', 'lol went down a rabbit hole to show the time zone of the post. I think I got it.');
INSERT INTO posts (date, subject, posts) VALUES (2021-05-24, 'database', 'got it to display the time stamp with time zone lol. Moving on to next step');
INSERT INTO posts (date, subject, posts) VALUES (2021-05-24, 'database', 'well it displays properly in the psql but not in the data.rows. oh well moving on to the next step. bigger fish to fry.');
INSERT INTO posts (date, subject, posts) VALUES (2021-05-24, 'project', 'Well, I think I am done for the day. I think I am at a good stopping point. I have the barebones of my server and index.html. I was able to send a GET request with the psql. I will work on the app.js tomorrow morning. I need a break.');
INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'overtime', 'working a little longer on the project before bed. kinda excited about what I can do. I am sure that will subside when I encounter real problems but really excited to prove what I am capable of.');
INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'New 2', 'its the begining of day two of my MVP project. Didnt sleep too much. My youngest was sick. Thats why there is coffee and I have a lot of it. :-)');
INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'database', 'I think I might have to change the data type of the posts column to varchar.....I am not sure if that will help ......');
INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'front end', 'well i just got the get request to work on the front end. I know have to display it. Things are making sense right now. feeling good.');
INSERT INTO posts (date, subject, posts) VALUES (CURRENT_TIMESTAMP, 'GET', 'displayed top 5 results on page, lets hope the good work keeps coming');